resolvers += Resolver.sonatypeRepo("releases")
addSbtPlugin("com.geirsson"        % "sbt-ci-release"    % "1.5.2")
addSbtPlugin("com.47deg"           % "sbt-microsites"    % "1.1.5")
addSbtPlugin("org.scoverage"       % "sbt-scoverage"     % "1.6.1")
addSbtPlugin("org.scalameta"       % "sbt-scalafmt"      % "2.3.3")
addSbtPlugin("org.scalameta"       % "sbt-mdoc"          % "2.1.3")
addSbtPlugin("com.eed3si9n"        % "sbt-unidoc"        % "0.4.3")
addSbtPlugin("de.heikoseeberger"   % "sbt-header"        % "5.4.0")
addSbtPlugin("com.alejandrohdezma" %% "sbt-github"       % "0.6.0")
addSbtPlugin("com.alejandrohdezma" % "sbt-github-header" % "0.6.0")
addSbtPlugin("com.alejandrohdezma" % "sbt-github-mdoc"   % "0.6.0")
addSbtPlugin("com.alejandrohdezma" % "sbt-mdoc-toc"      % "0.2")
